### ISSUE TITLE
Lussac crash if log are present and that absolute path is wrong

### ISSUE THREAD

**Issue by llobetv** [BarbourLab/lussac#2]
Would be nice if it could just erase old log. 
Maybe also add one parameters to say if you want to load logs or not

**Comment by DradeAW** [comment]
I don't particularly like the idea of automatically erasing an entire directory without it being explicit for the user.
But it is the logs, so maybe it's ok ... I need to think about it

I can definitely add a parameter to know if people want to load from logs or re-run on top of it and deleting the old logs :)

**Comment by llobetv** [comment]
If you add erase log parameter, also allow to erase old phy files :)


**********************************
******** export_to_phy_0 *********
**********************************
Running category 'all':
        - Sorting  clip_size_60_freq_min_300_freq_max_6000_freq_wid_1000Traceback (most recent call last):
  File "/users/nsr/llobet/miniconda3/envs/lussac/bin/lussac", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/export/home1/users/nsr/llobet/lussac/src/lussac/main.py", line 67, in main
    pipeline.launch()
  File "/export/home1/users/nsr/llobet/lussac/src/lussac/core/pipeline.py", line 60, in launch
    self._run_mono_sorting_module(module, module_key, category, params)
  File "/export/home1/users/nsr/llobet/lussac/src/lussac/core/pipeline.py", line 99, in _run_mono_sorting_module
    sub_sorting = module_instance.run(params0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/export/home1/users/nsr/llobet/lussac/src/lussac/modules/export_to_phy.py", line 49, in run
    export_to_phy(wvf_extractor, output_folder, **params['export_params'])
  File "/users/nsr/llobet/miniconda3/envs/lussac/lib/python3.11/site-packages/spikeinterface/exporters/to_phy.py", line 119, in export_to_phy
    raise FileExistsError(f"{output_folder} already exists")

**Comment by DradeAW** [comment]
You can erase old phy files by setting the parameter `remove_if_exists` to `True` (by default `False` to not erase any previous work)

https://github.com/SpikeInterface/spikeinterface/blob/d71316a0420cdac6b17020fc72d39dd43a1ff6ad/src/spikeinterface/exporters/to_phy.py#L33

**Comment by DradeAW** [comment]
I added a parameter `overwrite_logs` in dev `dev` branch.
If set to `true`, at the beginning of the run, Lussac will check for an existing folder, and if it exists, it deletes it.

Is this what you were looking for?
Is the issue resolved?
