### ISSUE TITLE
 The sorting object has spikes exceeding the recording duration

### ISSUE THREAD

**Issue by llobetv** [BarbourLab/lussac#4]
I suspect that is cause by realignment or spike close to end/begining where lussac try to extract after the end or before the begining?

One line could be add to remove those spikes from sorting object? (or if it's to calculate mean wf exclude them for this step?

**********************************
********** merge_units ***********
**********************************
Running category 'CS':
        - Sorting  clip_size_20_freq_max_2000_add_end_clip_45 (Done in 21.2 s)
        - Sorting  clip_size_40_freq_min_600_freq_max_6000_freq_wid_1000 (Done in 18.7 s)
        - Sorting  clip_size_40_freq_min_800_freq_max_10000_freq_wid_1000_detect_threshold_2.5 (Done in 14.8 s)
        - Sorting  clip_size_50_freq_min_150_freq_max_2000_freq_wid_1000 (Done in 18.1 s)
        - Sorting  clip_size_60_freq_min_300_freq_max_6000_freq_wid_1000 (Done in 16.4 s)
        - Sorting  clip_size_120_freq_min_60_freq_max_1000_freq_wid_300 (Done in 17.0 s)
        - Sorting  ks2_CS            Traceback (most recent call last): 

 File "/mnt/data/llobet/lussac/src/lussac/main.py", line 67, in main   
    pipeline.launch()
  File "/mnt/data/llobet/lussac/src/lussac/core/pipeline.py", line 60, in launch
    self._run_mono_sorting_module(module, module_key, category, params) 
  File "/mnt/data/llobet/lussac/src/lussac/core/pipeline.py", line 99, in _run_mono_sorting_module
    sub_sorting = module_instance.run(params0)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/llobet/lussac/src/lussac/modules/merge_units.py", line 55, in run
    wvf_extractor = self.extract_waveforms(**params['wvf_extraction'])  
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^  
  File "/mnt/data/llobet/lussac/src/lussac/core/module.py", line 186, in extract_waveforms
    return si.extract_waveforms(recording, sorting, folder_path, allow_unfiltered=True, **params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/llobet/miniconda3/envs/lussac/lib/python3.11/site-packages/spikeinterface/core/waveform_extractor.py", line 1567, in extract_waveforms
    we = WaveformExtractor.create(
         ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/mnt/data/llobet/miniconda3/envs/lussac/lib/python3.11/site-packages/spikeinterface/core/waveform_extractor.py", line 251, in create
    raise ValueError(
ValueError: The sorting object has spikes exceeding the recording duration. You have to remove those spikes with the `spikeinterface.curation.remove_excess_spikes()` function
/mnt/data/llobet/miniconda3/envs/lussac/lib/python3.11/site-packages/numba/np/ufunc/parallel.py:371: NumbaWarning:

**Comment by DradeAW** [comment]
I added a patch in the `align_units` module to take care of the spikes going over the edge of the recording.
I also added the corresponding unit tests.

Can you pull the latest commit from the `dev` branch and confirm whether it solves your issue?
You will  have to remove the logs for `align_units` and all modules after it.

Thanks for the report!

**Comment by llobetv** [comment]
Fix works thanks !
